/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import controlador.GestionEspecialidad;
import controlador.GestionPersonas;
import controlador.GestionTurno;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Especialidad;
import modelo.Persona;
import modelo.Turno;

/**
 *
 * @author Bernardo
 */
public class Vent_Turno extends javax.swing.JInternalFrame {

    int numMed=0;
    int id_persona=0 ;
    /**
     * Creates new form Turno
     */
    public Vent_Turno() {
        
        initComponents();
        Llenar();
        DatosTurno();
        
        numt.setText(String.valueOf(codigoTur()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fect = new javax.swing.JTextField();
        pact = new javax.swing.JTextField();
        medBox = new javax.swing.JComboBox<>();
        numt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        nomp = new javax.swing.JLabel();
        tep = new javax.swing.JLabel();
        app = new javax.swing.JLabel();
        tel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1342, 685));
        setMinimumSize(new java.awt.Dimension(1342, 685));
        setPreferredSize(new java.awt.Dimension(1342, 685));

        jLabel1.setText("NUMERO DE TURNO :");

        jLabel2.setText("FECHA :");

        jLabel3.setText("DNI-PACIENTE :");

        jLabel4.setText("MEDICO :");

        fect.setEnabled(false);

        medBox.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        medBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        medBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                medBoxMouseClicked(evt);
            }
        });
        medBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medBoxActionPerformed(evt);
            }
        });

        numt.setEnabled(false);
        numt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numtActionPerformed(evt);
            }
        });

        jButton1.setText("GENERAR TURNO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("BUSCAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pact, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(medBox, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(numt, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(fect, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nomp, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(app, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tep, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomp, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(app, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tep, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(medBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(92, 92, 92))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void medBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medBoxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_medBoxMouseClicked

    private void medBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medBoxActionPerformed
        // TODO add your handling code here:
        Persona esp= new GestionPersonas().getBuscarnombre((String.valueOf(medBox.getSelectedItem()).trim()));
        
        numMed=esp.getPer_id();
    }//GEN-LAST:event_medBoxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        Persona per=new GestionPersonas().getBuscarCedula(pact.getText());
        
        
        if(per!=null){
             id_persona = per.getPer_id();
            nomp.setText(per.getPer_nombre());
            app.setText(per.getPer_apellido());
            tep.setText(per.getPer_direccion());
            tel.setText(per.getPer_telefono());
            
           
            
        
        }else {
            
            JOptionPane.showMessageDialog(null,"Paciente no exite");
            
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        java.util.Date utilDate = new java.util.Date();
       java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
        
        
        new GestionTurno().IngresarTurno(new Turno(codigoid(),id_persona ,numMed,codigoTur(),sqlDate));
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void numtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel app;
    javax.swing.JTextField fect;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> medBox;
    private javax.swing.JLabel nomp;
    private javax.swing.JTextField numt;
    private javax.swing.JTextField pact;
    private javax.swing.JLabel tel;
    private javax.swing.JLabel tep;
    // End of variables declaration//GEN-END:variables

    
         public void Llenar(){
         // TODO add your handling code here:
         ArrayList<String>listE=new GestionPersonas().getListMedicos();
             //JOptionPane.showMessageDialog(null,listE.size());
        for(int i=0;i< listE.size();i++){
           
                medBox.addItem(listE.get(i));
            
           
            
        
    }
    }

    private void DatosTurno() {
         java.util.Date utilDate = new java.util.Date();
       java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
        fect.setText(String.valueOf((Date)sqlDate));
    }
    
    
    public int codigoid(){
   List<Turno>lispro=new GestionTurno().getListTurnos();
           
   ArrayList<Integer>lis=new ArrayList<>();
   
       for (int i = 0; i < lispro.size(); i++) {
           lis.add(lispro.get(i).getTur_id());
           
       }
       
       Collections.sort(lis);
       
       int n=lis.get(lis.size()-1)+1;
    
   
        return n;
   
   }
    
    
    public int codigoTur(){
   List<Turno>lispro=new GestionTurno().getListTurnos();
           
   ArrayList<Integer>lis=new ArrayList<>();
   
       for (int i = 0; i < lispro.size(); i++) {
           lis.add(lispro.get(i).getTur_num());
           
       }
       
       Collections.sort(lis);
       
       int n=lis.get(lis.size()-1)+1;
    
   
        return n;
   
   }
}
