/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Gestion;

import controlador.GestionPersonas;

import java.sql.Date;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;

import modelo.Persona;


/**
 *
 * @author Bernardo
 */
public class Vent_Empleados extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vent_Clientes
     */
    public Vent_Empleados() {
        initComponents();
        setClosable(true);
        setDefaultLocale(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lcod = new javax.swing.JTextField();
        jced = new javax.swing.JTextField();
        jnom = new javax.swing.JTextField();
        jape = new javax.swing.JTextField();
        jeda = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jcar = new javax.swing.JTextField();
        a = new javax.swing.JRadioButton();
        e = new javax.swing.JRadioButton();
        jcorr = new javax.swing.JTextField();
        jusu = new javax.swing.JTextField();
        jcont = new javax.swing.JTextField();
        jtel = new javax.swing.JTextField();
        jdir = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setAlignmentX(0.2F);
        setAlignmentY(0.2F);
        setMaximumSize(new java.awt.Dimension(1342, 685));
        setMinimumSize(new java.awt.Dimension(1342, 685));
        setPreferredSize(new java.awt.Dimension(1342, 685));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setBackground(new java.awt.Color(255, 255, 153));
        tabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabla.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        tabla.setModel(new Tabla_Empleados());
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 25, 890, -1));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(1, 5));

        jButton1.setBackground(new java.awt.Color(0, 0, 51));
        jButton1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ACTUALIZAR");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton4.setBackground(new java.awt.Color(0, 0, 51));
        jButton4.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("ELIMINAR");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        jButton2.setBackground(new java.awt.Color(0, 0, 51));
        jButton2.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("BUSCAR");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton5.setBackground(new java.awt.Color(0, 0, 51));
        jButton5.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("LISTAR");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);

        jButton3.setBackground(new java.awt.Color(0, 0, 51));
        jButton3.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("REGISTRAR");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 601, 1330, 50));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridLayout(1, 2));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(11, 1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CODIGO :");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel9);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CEDULA :");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NOMBRE :");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("APELLIDO :");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel3);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("FEC_NACI(A/M/D) :");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel10);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CARGO : ");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel6);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("CORREO :");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel11);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("GENERO :");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel4);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("CONTRASEÑA :");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel7);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("TELEFONO:");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel5);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("DIRECCION :");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel8);

        jPanel4.add(jPanel2);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(11, 1));

        lcod.setEditable(false);
        lcod.setBackground(new java.awt.Color(204, 204, 204));
        lcod.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lcod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(lcod);

        jced.setBackground(new java.awt.Color(204, 204, 204));
        jced.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jced.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jced.setAlignmentX(0.2F);
        jced.setAlignmentY(0.2F);
        jPanel3.add(jced);

        jnom.setBackground(new java.awt.Color(204, 204, 204));
        jnom.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jnom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jnom.setAlignmentX(0.2F);
        jnom.setAlignmentY(0.2F);
        jPanel3.add(jnom);

        jape.setBackground(new java.awt.Color(204, 204, 204));
        jape.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jape.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jape.setAlignmentX(0.2F);
        jape.setAlignmentY(0.2F);
        jPanel3.add(jape);

        jeda.setBackground(new java.awt.Color(204, 204, 204));
        jeda.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jeda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jeda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jedaMouseClicked(evt);
            }
        });
        jPanel3.add(jeda);

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));
        jPanel5.setLayout(new java.awt.GridLayout(1, 3));

        jcar.setEditable(false);
        jcar.setBackground(new java.awt.Color(204, 204, 204));
        jcar.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jcar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jcar.setAlignmentX(0.2F);
        jcar.setAlignmentY(0.2F);
        jPanel5.add(jcar);

        a.setBackground(new java.awt.Color(255, 102, 102));
        a.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        a.setText("A");
        a.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        jPanel5.add(a);

        e.setBackground(new java.awt.Color(255, 102, 102));
        e.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        e.setText("E");
        e.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eActionPerformed(evt);
            }
        });
        jPanel5.add(e);

        jPanel3.add(jPanel5);

        jcorr.setBackground(new java.awt.Color(204, 204, 204));
        jcorr.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jcorr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(jcorr);

        jusu.setBackground(new java.awt.Color(204, 204, 204));
        jusu.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jusu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(jusu);

        jcont.setBackground(new java.awt.Color(204, 204, 204));
        jcont.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jcont.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(jcont);

        jtel.setBackground(new java.awt.Color(204, 204, 204));
        jtel.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jtel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtel.setAlignmentX(0.2F);
        jtel.setAlignmentY(0.2F);
        jPanel3.add(jtel);

        jdir.setBackground(new java.awt.Color(204, 204, 204));
        jdir.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jdir.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jdir.setAlignmentX(0.2F);
        jdir.setAlignmentY(0.2F);
        jPanel3.add(jdir);

        jPanel4.add(jPanel3);

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 410, 500));

        jLabel12.setBackground(new java.awt.Color(153, 153, 0));
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel12.setOpaque(true);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
   
    
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Persona per=new Persona();
        java.util.Date utilDate= new java.util.Date();
       
        utilDate=Date.valueOf(jeda.getText());
        
        
        
        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
      
        if(new Gestion().Cedula(jced.getText()) && jced.getText().length()==10){
            
        if(!Existe(jced.getText())){
            if(jcar.getText().length()==1){
             if(jcar.getText().equals("A") || jcar.getText().equals("E")  ){
        per.setPer_id(codigoid());
        per.setPer_cedula(jced.getText());
        per.setPer_nombre(jnom.getText().toUpperCase());
        per.setPer_apellido(jape.getText().toUpperCase());
        per.setPer_direccion(jdir.getText().toUpperCase());
        per.setPer_telefono(jtel.getText());
        per.setPer_fec_nac(sqlDate);
       
        per.setPer_rol(jcar.getText().toUpperCase());
        per.setPer_clave(jcont.getText());
        per.setPer_genero(jusu.getText());
        per.setPer_email(jcorr.getText());
         new GestionPersonas().InsertPersona(per);
         JOptionPane.showMessageDialog(null,"REGISTRO CORRECTO");
        
        
        }else{
               JOptionPane.showMessageDialog(null,"TIPO DE CARGO INCORRECTO (A-E)");           
         }
        
            }else{
             JOptionPane.showMessageDialog(null,"TIPO DE CARGO DEMACIADO LARGO SOLO DE ADMITE UN CARACTER");      
            
            }
        
        
        }  else{
        JOptionPane.showMessageDialog(null,"PERSONA YA REGISTRADA");
        }  
            
        }else {
        
            JOptionPane.showMessageDialog(null,"CEDULA INCORRECTA");
        }
       
       
     
      
        
       
       
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         ArrayList<Persona>lisemp=new ArrayList<>();
        ArrayList<Persona>listotal=new GestionPersonas().getListPersonas();
        
        for (int i = 0; i < listotal.size(); i++) {
            
            if(listotal.get(i).getPer_rol().equals("A") || listotal.get(i).getPer_rol().equals("E") ){
                lisemp.add(listotal.get(i));
            
            }
        }
       tabla.setModel(new Tabla_Empleados(lisemp));
       
       // System.out.println(new GestionPersonas().getBuscarCliente("1").getPer_id());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        //System.out.println(codigo(getlista()));
        if(Existe(jced.getText())){
            
        Persona per=new GestionPersonas().getBuscarCedula(jced.getText());
        
        if(per.getPer_rol().equals("A")||per.getPer_rol().equals("E") ){
        
        lcod.setText(String.valueOf(per.getPer_id()));
        jced.setText(per.getPer_cedula());
        jnom.setText(per.getPer_nombre());
        jape.setText(per.getPer_apellido());
        jcar.setText(per.getPer_rol());
        jusu.setText(per.getPer_genero());
        jcont.setText(per.getPer_clave());
        jdir.setText(per.getPer_direccion());
        jtel.setText(per.getPer_telefono());
        jcorr.setText(per.getPer_email());
        
        jeda.setText(String.valueOf((Date)per.getPer_fec_nac()));
        
        }else{
                
                 JOptionPane.showMessageDialog(null,"EMPLEADO NO EXISTE");
                
        }
       
        
         } else {
                
                JOptionPane.showMessageDialog(null,"EMPLEADO NO EXISTE");
          }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:
        //jnom.setText((String) tabla.getValueAt(tabla.getSelectedRow(), tabla.getSelectedColumn()));
        lcod.setText(String.valueOf(tabla.getValueAt(tabla.getSelectedRow(), 0)));
        jced.setText((String) tabla.getValueAt(tabla.getSelectedRow(), 1));
        jnom.setText((String) tabla.getValueAt(tabla.getSelectedRow(), 2));
        jape.setText((String) tabla.getValueAt(tabla.getSelectedRow(), 3));
        jcorr.setText((String) tabla.getValueAt(tabla.getSelectedRow(), 4));
        jcar.setText((String) tabla.getValueAt(tabla.getSelectedRow(), 5));
        jusu.setText((String) tabla.getValueAt(tabla.getSelectedRow(), 6));
        jcont.setText((String) tabla.getValueAt(tabla.getSelectedRow(), 7));
        jdir.setText((String) tabla.getValueAt(tabla.getSelectedRow(), 8));
        jtel.setText((String) tabla.getValueAt(tabla.getSelectedRow(), 9));
        jeda.setText(String.valueOf(tabla.getValueAt(tabla.getSelectedRow(), 10)));
        //lcod1.setText(String.valueOf(tabla.getValueAt(tabla.getSelectedRow(), 10)));
    
       
    }//GEN-LAST:event_tablaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Persona per=new Persona();
         java.util.Date utilDate= new java.util.Date();
       
        utilDate=Date.valueOf(jeda.getText());
        
        
        
        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
        per.setPer_id(Integer.parseInt(lcod.getText()));
        per.setPer_cedula(jced.getText());
        per.setPer_nombre(jnom.getText());
        per.setPer_apellido(jape.getText());
        per.setPer_direccion(jdir.getText());
        per.setPer_telefono(jtel.getText());
        per.setPer_fec_nac(sqlDate);
        per.setPer_rol(jcar.getText());
        per.setPer_clave(jcont.getText());
        per.setPer_genero(jusu.getText());
        per.setPer_email(jcorr.getText());
        
        
        
        
        new GestionPersonas().ActualizarPersona(per);
        JOptionPane.showMessageDialog(null,"ACTULIZACION CORRECTA");
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       
        new GestionPersonas().EliminarPersona(jced.getText());
        JOptionPane.showMessageDialog(null,"ELIMINACION CORRECTA");
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jedaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jedaMouseClicked

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
         if(a.isSelected()){
        jcar.setText("A");
       
        e.setSelected(false);
        }
         
   a.setSelected(true);
    }//GEN-LAST:event_aActionPerformed

    private void eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eActionPerformed
        // TODO add your handling code here:
         if(e.isSelected()){
        jcar.setText("E");
       
        a.setSelected(false);
        }
         e.setSelected(true);
    }//GEN-LAST:event_eActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton a;
    private javax.swing.JRadioButton e;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jape;
    private javax.swing.JTextField jcar;
    private javax.swing.JTextField jced;
    private javax.swing.JTextField jcont;
    private javax.swing.JTextField jcorr;
    private javax.swing.JTextField jdir;
    private javax.swing.JTextField jeda;
    private javax.swing.JTextField jnom;
    private javax.swing.JTextField jtel;
    private javax.swing.JTextField jusu;
    private javax.swing.JTextField lcod;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

  public boolean Existe(String cedula){
    
        boolean exi=false;
        ArrayList<Persona>lis=new GestionPersonas().getListPersonas();
        
        for (int i = 0; i < lis.size(); i++) {
            if(lis.get(i).getPer_cedula().equals(cedula)){
               exi=true;
               break;
            
            }  
            
        }
        
        
    
    return exi;
    }

public int  codigo(ArrayList<Integer>lis){
      boolean n=false;
      int num=1;
        while (n==false) {      
             num=new Random().nextInt(100)+0;
            if(!new GestionPersonas().comparar(num, lis)){
               n=true;
            
            }
        }

      return num;
     }
    
    public  ArrayList<Integer>getlista(){
        ArrayList<Integer>list=new ArrayList<>();
        ArrayList<Persona>list1=new GestionPersonas().getListPersonas();
        for (int i = 0; i < list1.size(); i++) {
            list.add(list1.get(i).getPer_id());
        }
    return list;
    }
    
     public int codigoid(){
   List<Persona>lispro=new GestionPersonas().getListPersonas();
           
   ArrayList<Integer>lis=new ArrayList<>();
   
       for (int i = 0; i < lispro.size(); i++) {
           lis.add(lispro.get(i).getPer_id());
           
       }
       
       Collections.sort(lis);
       
       int n=lis.get(lis.size()-1)+1;
    
   
        return n;
   
   }
   


}

